"use client";

import { ClientProvider } from "@/providers/ClientContext";
import "./globals.css";
import { Inter } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import Header from "@/components/Header";
import Modal from "@/components/Modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <ToastContainer />
        <Header />
        <ClientProvider>
          <Modal />
          {children}
        </ClientProvider>
      </body>
    </html>
  );
}
