import { ClientProvider } from "@/providers/ClientContext";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Modal from "@/components/Modal";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100`} suppressHydrationWarning={true}>
        <Header />
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
        <ClientProvider>
          {/* <Modal /> */}
          {children}
        </ClientProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
